name: Release Pull Request

on:
  pull_request: 
    branches: ["master"]

jobs:
  Package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - name: Install dependencies (CI)
        run: npm ci

      - name: Run Unit Tests
        run: npm test
      
      - name: Define package variables (name-version)
        run: |
            #bash
            PACKAGE_NAME=$(cat package.json | grep 'name' | cut -d '"' -f 4)
            PACKAGE_VERSION=$(cat package.json | grep 'version' | cut -d '"' -f 4)-${{github.run_number}}
            echo "PACKAGE_FILE=$PACKAGE_NAME-$PACKAGE_VERSION.tgz" >> $GITHUB_ENV
            npm version $PACKAGE_VERSION

      - name: Build
        run: npm run build

      - run: npm pack ./dist
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ${{ env.PACKAGE_FILE }}
    
  Publish:
    needs: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: package
          path: package.tgz
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: tar -xf package.tgz
      - run: ls package
        # env:
          # NODE_AUTH_TOKEN: ${{secrets.npm_token}}
